version: '3.8'

services:
  db:
    image: postgres:15
    command: -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: "W@t#rSens0rs"
      POSTGRES_DB: water-sensors
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -c 'select 1'
      interval: 1s
      timeout: 1s
      retries: 20
  flyway:
    image: flyway/flyway
    command: "-url=jdbc:postgresql://db/water-sensors -user=postgres -password=\"W@t#rSens0rs\" -connectRetries=60 migrate"
    environment:
      FLYWAY_EDITION: community
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
volumes:
  pgdata:
  